"""Candidate local-NTFS handle observations; public admission is separate.

Imports are inert. Never open, read, close or mutate the caller's live HANDLE.
Identity is contextual metadata, not path, content or access-policy admission.
"""

import ctypes
import os
import platform
import struct
import sys
from collections.abc import Callable
from threading import Lock
from typing import Protocol, cast

from mos_eisley.platform.identity import (
    IdentityQueryError,
    UnsupportedPlatformError,
    WindowsFileIdentity,
    WindowsHandle,
)

_DWORD = ctypes.c_uint32
# Read-only, mounted, autogenerated name, secure-open, PnP and appcontainer
# traversal characteristics do not change this read-only identity scope. Refuse
# all other bits, including remote/removable/virtual/TS/WebDAV/portable/CSV.
_QUALIFIED_CHARACTERISTICS = 0x0002 | 0x0020 | 0x0080 | 0x0100 | 0x0800 | 0x20000
_STATUS_PENDING = 0x103


class DeviceInformation(ctypes.Structure):
    _fields_ = [("device_type", _DWORD), ("characteristics", _DWORD)]


class IoStatus(ctypes.Structure):
    # The first member is a union of NTSTATUS and PVOID, hence pointer width.
    _fields_ = [("status", ctypes.c_void_p), ("information", ctypes.c_size_t)]


class StandardInformation(ctypes.Structure):
    _fields_ = [
        ("allocation_size", ctypes.c_int64),
        ("end_of_file", ctypes.c_int64),
        ("links", _DWORD),
        ("delete_pending", ctypes.c_ubyte),
        ("directory", ctypes.c_ubyte),
    ]


class IdInformation(ctypes.Structure):
    _fields_ = [("volume_serial", ctypes.c_uint64), ("file_id", ctypes.c_ubyte * 16)]


class NativeFileError(OSError):
    def __init__(self, code: int) -> None:
        super().__init__("native file observation failed")
        self.native_code = code


class FileApi(Protocol):
    def disk(self, handle: int) -> bool: ...
    def device(self, handle: int) -> tuple[int, int]: ...
    def filesystem(self, handle: int) -> str: ...
    def standard(self, handle: int) -> None: ...
    def identity(self, handle: int) -> WindowsFileIdentity: ...


class _NativeFunction(Protocol):
    argtypes: list[object]
    restype: object

    def __call__(self, *args: object) -> int: ...


class _WindowsVersion(Protocol):
    build: int


def _symbol(library: object, name: str) -> object:
    return getattr(library, name)


def _last_error() -> int:
    return cast(Callable[[], int], _symbol(ctypes, "get_last_error"))()


# A pending native write must outlive a rejected query. Keep at most one pair
# for process lifetime; after that anomalous result all device queries refuse.
_pending: tuple[IoStatus, DeviceInformation] | None = None
_device_lock = Lock()


class NativeFileApi:
    def __init__(self) -> None:
        loader = cast(Callable[..., object], _symbol(ctypes, "WinDLL"))
        kernel = loader("kernel32.dll", use_last_error=True, winmode=0x0800)
        native = loader("ntdll.dll", use_last_error=True, winmode=0x0800)
        self._type = cast(_NativeFunction, _symbol(kernel, "GetFileType"))
        self._volume = cast(
            _NativeFunction, _symbol(kernel, "GetVolumeInformationByHandleW")
        )
        self._information = cast(
            _NativeFunction, _symbol(kernel, "GetFileInformationByHandleEx")
        )
        self._device = cast(
            _NativeFunction, _symbol(native, "NtQueryVolumeInformationFile")
        )
        self._type.argtypes = [ctypes.c_void_p]
        self._type.restype = _DWORD
        self._volume.argtypes = [
            ctypes.c_void_p,
            ctypes.c_void_p,
            _DWORD,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            _DWORD,
        ]
        self._volume.restype = ctypes.c_int32
        self._information.argtypes = [
            ctypes.c_void_p,
            ctypes.c_int32,
            ctypes.c_void_p,
            _DWORD,
        ]
        self._information.restype = ctypes.c_int32
        self._device.argtypes = [
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            _DWORD,
            ctypes.c_int32,
        ]
        self._device.restype = ctypes.c_int32

    def disk(self, handle: int) -> bool:
        kind = self._type(handle)
        if kind == 0:
            raise NativeFileError(_last_error())
        return kind == 1

    def device(self, handle: int) -> tuple[int, int]:
        global _pending
        with _device_lock:
            if _pending is not None:
                raise ValueError("native volume completion is unqualified")
            # Allocate the retention pair before entering native code, so even
            # an allocation failure after a pending result cannot free outputs.
            owned = (IoStatus(), DeviceInformation())
            status, device = owned
            # Retain before entry too: a Python/FFI exception while examining
            # completion must not release potentially pending output storage.
            _pending = owned
            result = self._device(
                handle,
                ctypes.byref(status),
                ctypes.byref(device),
                ctypes.sizeof(device),
                4,
            )
            # Read NTSTATUS from its union's low 32 bits, not padding bytes.
            completion = ctypes.c_int32.from_buffer(status).value
            if result == _STATUS_PENDING or completion == _STATUS_PENDING:
                raise NativeFileError(_STATUS_PENDING)
            _pending = None
            if result != 0:
                raise NativeFileError(result)
            if completion != 0 or status.information != ctypes.sizeof(device):
                raise ValueError("native volume result is malformed")
            return device.device_type, device.characteristics

    def filesystem(self, handle: int) -> str:
        # Microsoft specifies MAX_PATH + 1 characters for this output.
        name = ctypes.create_unicode_buffer(261)
        if not self._volume(handle, None, 0, None, None, None, name, len(name)):
            raise NativeFileError(_last_error())
        if "\0" not in name[:]:
            raise ValueError("native filesystem name is unterminated")
        return name.value

    def standard(self, handle: int) -> None:
        value = StandardInformation()
        if not self._information(handle, 1, ctypes.byref(value), ctypes.sizeof(value)):
            raise NativeFileError(_last_error())
        if value.directory not in (0, 1) or value.delete_pending not in (0, 1):
            raise ValueError("native file information is malformed")

    def identity(self, handle: int) -> WindowsFileIdentity:
        value = IdInformation()
        if not self._information(handle, 18, ctypes.byref(value), ctypes.sizeof(value)):
            raise NativeFileError(_last_error())
        return WindowsFileIdentity(value.volume_serial, bytes(value.file_id))


_bindings: NativeFileApi | None = None
_binding_lock = Lock()


def _file_api() -> NativeFileApi:
    global _bindings
    with _binding_lock:
        if _bindings is None:
            _bindings = NativeFileApi()
        return _bindings


def _require_candidate_host() -> None:
    if (
        sys.platform != "win32"
        or os.name != "nt"
        or struct.calcsize("P") != 8
        or platform.machine().upper() != "AMD64"
    ):
        raise UnsupportedPlatformError("native file identity target is unsupported")
    version = cast(Callable[[], _WindowsVersion], _symbol(sys, "getwindowsversion"))()
    if version.build < 17763:
        raise UnsupportedPlatformError("native file identity target is unsupported")


def _query_identity(api: FileApi, handle: int) -> WindowsFileIdentity:
    if not api.disk(handle):
        raise ValueError("native object type is unqualified")
    device_type, characteristics = api.device(handle)
    # Native disk and disk-filesystem device objects are distinct from the
    # network, CD-ROM and virtual-disk device types. NTFS + StandardInfo below
    # additionally refuse direct/raw devices and other filesystems.
    if device_type not in (7, 8) or characteristics & ~_QUALIFIED_CHARACTERISTICS:
        raise ValueError("native storage device is unqualified")
    if api.filesystem(handle) != "NTFS":
        raise ValueError("native filesystem is unqualified")
    api.standard(handle)
    return api.identity(handle)


def file_identity(opened: WindowsHandle) -> WindowsFileIdentity:
    """Observe a borrowed live local-NTFS file/directory HANDLE for qualification.

    Caller prevents concurrent close/reuse. No path lookup, ownership transfer or
    storage authorization. The public selector remains closed pending admission.
    """
    if type(opened) is not WindowsHandle:
        raise ValueError("native file identity requires a typed borrowed HANDLE")
    _require_candidate_host()
    try:
        return _query_identity(_file_api(), opened.value)
    except (OSError, ValueError, MemoryError, AttributeError) as error:
        raise IdentityQueryError("opened-file identity query failed") from error
