"""Async broker lifecycle; cancellation never abandons owned host operations."""

from __future__ import annotations

import asyncio
import math
import re
from collections.abc import Callable
from typing import TYPE_CHECKING
from uuid import uuid4

from pydantic import JsonValue, TypeAdapter

from mos_eisley.run.duplex import CLAIM_LIMIT, ExchangeHandler, bounded_exchange
from mos_eisley.run.process import bounded_process
from mos_eisley.run.watchdog import WatchdogHandle, arm_watchdog, remove_exact

if TYPE_CHECKING:
    from mos_eisley.run.isolation import OfflineContainer


class _OwnedOperations:
    def __init__(self) -> None:
        self.cancelled = False

    async def thread[T](self, call: Callable[[], T]) -> T:
        # Setup may return a newly owned container/guardian. Capture the result
        # before delivering cancellation, so the caller can clean it up exactly.
        task = asyncio.create_task(asyncio.to_thread(call))
        while not task.done():
            try:
                await asyncio.shield(task)
            except asyncio.CancelledError:
                self.cancelled = True
        return task.result()

    def check_cancelled(self) -> None:
        if self.cancelled:
            raise asyncio.CancelledError

    async def exchange(self, task: asyncio.Task[bytes]) -> bytes:
        forwarded = False
        while not task.done():
            try:
                await asyncio.shield(task)
            except asyncio.CancelledError:
                self.cancelled = True
                if not forwarded:
                    # Exactly one cancellation reaches the duplex task. Further
                    # caller cancels cannot interrupt its handler/pipe teardown.
                    task.cancel()
                    forwarded = True
        result = task.result()
        self.check_cancelled()
        return result


async def exchange_in_container(
    container: OfflineContainer,
    arguments: tuple[str, ...],
    payload: bytes,
    handler: ExchangeHandler,
    timeout: float,
) -> bytes:
    if (
        len(payload) > CLAIM_LIMIT
        or b"\n" in payload
        or not math.isfinite(timeout)
        or not 0 < timeout <= 60
    ):
        raise ValueError("invalid isolated exchange bounds")
    owned = _OwnedOperations()
    metadata_bytes = await owned.thread(
        lambda: bounded_process(
            [container.docker, "image", "inspect", container.image_id], limit=1_000_000
        )
    )
    owned.check_cancelled()
    metadata = TypeAdapter(list[dict[str, JsonValue]]).validate_json(metadata_bytes)
    if len(metadata) != 1 or metadata[0].get("Id") != container.image_id:
        raise ValueError("image identity or implicit volume configuration is invalid")
    config = metadata[0].get("Config")
    if not isinstance(config, dict) or config.get("Volumes"):
        raise ValueError("image configuration permits implicit volumes")
    name = "mos-eval-" + uuid4().hex
    container_id: str | None = None
    watchdog: WatchdogHandle | None = None
    container.lifecycle_path = None

    def cleanup() -> None:
        if watchdog is not None:
            try:
                assert container_id is not None
                remove_exact(container.docker, container_id)
            finally:
                watchdog.finish()
        elif container_id is not None:
            remove_exact(container.docker, container_id)
        else:
            # A lost create response can still leave a container. This name is
            # generated by this call; caller input can never select the target.
            bounded_process(
                [container.docker, "rm", "--force", name], timeout=10, limit=65536
            )

    try:
        created = await owned.thread(
            lambda: bounded_process(
                container.create_command(name, arguments), limit=65536
            )
        )
        candidate_id = created.decode("ascii").strip()
        if not re.fullmatch(r"[0-9a-f]{64}", candidate_id):
            raise ValueError("Docker did not return a full container ID")
        container_id = candidate_id
        owned.check_cancelled()
        watchdog = await owned.thread(
            lambda: arm_watchdog(
                container.docker, candidate_id, container.lifecycle_root, timeout + 5
            )
        )
        container.lifecycle_path = watchdog.directory
        owned.check_cancelled()
        output = await owned.exchange(
            asyncio.create_task(
                bounded_exchange(
                    [
                        container.docker,
                        "start",
                        "--attach",
                        "--interactive",
                        candidate_id,
                    ],
                    payload,
                    handler,
                    timeout,
                )
            )
        )
        exit_code = await owned.thread(
            lambda: bounded_process(
                [
                    container.docker,
                    "inspect",
                    "--format",
                    "{{.State.ExitCode}}",
                    candidate_id,
                ],
                limit=65536,
            )
        )
        owned.check_cancelled()
        if exit_code.strip() != b"0":
            raise ValueError("isolated worker failed")
        return output
    finally:
        await owned.thread(cleanup)
        owned.check_cancelled()
